name: Build static web page

on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository == 'jotavalla/learningReflex2'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run build script
        run: bash remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
          commit_user_name: Jota Valla
          commit_user_email: djimmyandersond10@gmail.com
          commit_author: jotavalla
          
        
  
